### ISSUE TITLE
Toml dump/parse doesn't handle keys that start with numbers properly

### ISSUE THREAD

**Issue by jhaynes** [emancu/toml-rb#79]
Depending on how one views the toml spec, either parse or dump are behaving incorrectly for keys that start with a number.

```
irb(main):001:0> require 'toml'
=> true
irb(main):002:0> t = {'10_foo': 'bar'}
=> {:"10_foo"=>"bar"}
irb(main):003:0> d = TOML.dump(t)
=> "10_foo = \"bar\"\n"
irb(main):004:0> p = TOML.parse(d)
TOML::ParseError: Failed to parse input on line 1 at offset 0
10_foo = "bar"

^
```

Note how the key winds up unquoted when it is dumped. 

```rb(main):005:0> TOML.parse("\"10_foo\" = \"bar\"\n")
=> {"10_foo"=>"bar"}```

behaves as expected.

If you want to call that a dumper issue, a potential fix is:

```
diff --git a/lib/toml/dumper.rb b/lib/toml/dumper.rb
index ca60426..4fbba97 100644
--- a/lib/toml/dumper.rb
+++ b/lib/toml/dumper.rb
@@ -90,11 +90,11 @@ module TOML
     end

     def bare_key?(key)
-      !!key.to_s.match(/^[a-zA-Z0-9_-]*$/)
+      !!key.to_s.match(/^[a-zA-Z][a-zA-Z0-9_-]*$/)
     end

     def quote_key(key)
-      '"' + key.gsub('"', '\\"') + '"'
+      '"' + key.to_s.gsub('"', '\\"') + '"'
     end
   end
 end
```

I haven't dug into the parser yet...

**Comment by emancu** [comment]
@jhaynes I'm sorry I didn't take care of this sooner. I will continue maintaining this gem frequently.

FWIW the issue was on the parser, because I was not accepting _bare keys_ starting with numbers, which is something valid on the new specs.

I'm submitting a fix in a few minutes.

Thank you for reporting this issue and using the gem.
